import { bestColumnOfRole } from "../../lib/analysis/pickColumns";
import type { PipelineResult } from "../../types/pipeline";
import { ChartRenderer } from "../workspace/lazy";
import { SkeletonLine } from "../workspace/Skeleton";
import { CircleDollarSign, Network } from "lucide-react";
import { findNarrative } from "./aiLookup";

export function PageAnalyses({ r }: { r: PipelineResult }) {
  const filtered = r.analyses.filter(a => !['comparison', 'concentration_analysis', 'segmentation'].includes(a.capability));
  const revenueColumn=bestColumnOfRole(r.semantics.columns,'revenue');
  const connectedRevenue=r.organization?.metrics?.find(metric=>metric.id==='connected-revenue')?.value;
  const revenue=connectedRevenue??(revenueColumn?r.engineeredRows.reduce((sum,row)=>sum+(Number(row[revenueColumn])||0),0):0);
  const inventoryCoverage=r.organization?.metrics?.find(metric=>metric.id==='inventory-demand-coverage');
  const stockReview=r.organization?.metrics?.find(metric=>metric.id==='products-requiring-review');
  return <div className="space-y-5"><section className="bi-heading"><div><div className="eyebrow"><span className="eyebrow-dot"/> BUSINESS INTELLIGENCE</div><h1>Commercial performance</h1><p>Decision-ready KPIs and analytical evidence from the active organisational workspace.</p></div>{r.organization&&<span><Network size={14}/>{r.organization.datasets.length} connected sources</span>}</section><section className="bi-kpi-grid"><article className="bi-revenue-kpi"><div><CircleDollarSign size={20}/><span>Recognised revenue</span></div><strong>{revenue?new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(revenue):'Not available'}</strong><p>{connectedRevenue!==undefined?'Connected sales source · reconciled organisational context':revenueColumn?`Calculated from ${revenueColumn}`:'A revenue measure was not detected'}</p></article><article><span>{inventoryCoverage?'Inventory coverage':'Transactions analysed'}</span><strong>{inventoryCoverage?`${inventoryCoverage.value.toFixed(1)}%`:r.source.rowCount.toLocaleString('en-GB')}</strong><p>{inventoryCoverage?'Against demand represented in the sales period':`${r.profile.columnCount} classified columns`}</p></article><article><span>{stockReview?'Products requiring review':'Data quality'}</span><strong>{stockReview?Math.round(stockReview.value):`${r.quality.overallScore}/100`}</strong><p>{stockReview?'Validate lead times and safety stock':'Decision-grade source integrity'}</p></article><article><span>Analytical coverage</span><strong>{r.capabilities.available.length}/{r.capabilities.capabilities.length}</strong><p>Capability-gated analyses available</p></article></section>{filtered.length?<div className="grid grid-cols-1 lg:grid-cols-2 gap-4">{filtered.map((a, i) => { const narrative = findNarrative(r.aiInsights, a.id, i); return <div key={a.id} className="bg-white rounded-[16px] border border-slate-200 p-4 shadow-sm"><ChartRenderer chart={a.chart} /><div className="mt-2">{r.aiLoading ? <SkeletonLine width="60%" /> : narrative ? <p className="text-xs text-slate-500 leading-5"><span className="font-semibold text-indigo-700">AI: </span>{narrative.narrative}</p> : <p className="text-xs text-slate-400">{a.explanation}</p>}</div></div>; })}</div>:<div className="bg-white rounded-[16px] border p-6 text-sm text-slate-500">No analyses could be generated.</div>}</div>;
}
