import { useEffect, useState } from 'react';
import { Building2, ShieldCheck, UserPlus, Users } from 'lucide-react';
import { getSupabase } from '../../lib/auth/supabaseClient';
import { useOrganizationAccess } from '../../lib/auth/useOrganizationAccess';

type Role = 'owner' | 'admin' | 'analyst' | 'viewer';
interface Organization { id: string; name: string; owner_user_id: string; }
interface Member { user_id: string; email: string; role: Role; }
interface Invitation { id: string; email: string; role: Exclude<Role,'owner'>; status: string; }

export function PageTeamWorkspace() {
  const access=useOrganizationAccess();
  const [organization,setOrganization]=useState<Organization|null>(null); const [members,setMembers]=useState<Member[]>([]); const [invitations,setInvitations]=useState<Invitation[]>([]);
  const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [role,setRole]=useState<Exclude<Role,'owner'>>('analyst'); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true);
  async function load(){const sb=getSupabase();if(!sb){setMessage('Supabase is not configured.');setLoading(false);return}const {data:{user}}=await sb.auth.getUser();if(!user){setMessage('Sign in to manage a team workspace.');setLoading(false);return}const {data:orgs}=await sb.from('organizations').select('id,name,owner_user_id').limit(1);const org=orgs?.[0] as Organization|undefined;setOrganization(org||null);if(org){const [{data:m},{data:i}]=await Promise.all([sb.from('organization_members').select('user_id,email,role').eq('organization_id',org.id),sb.from('organization_invitations').select('id,email,role,status').eq('organization_id',org.id).order('created_at',{ascending:false})]);setMembers((m||[]) as Member[]);setInvitations((i||[]) as Invitation[])}setLoading(false)}
  useEffect(()=>{void load()},[]);
  async function create(){const sb=getSupabase();if(!sb||!name.trim())return;setMessage('');const {data:{user}}=await sb.auth.getUser();if(!user)return;const {data:org,error}=await sb.from('organizations').insert({name:name.trim(),owner_user_id:user.id}).select().single();if(error){setMessage(error.message);return}const member=await sb.from('organization_members').insert({organization_id:org.id,user_id:user.id,email:user.email||'',role:'owner'});if(member.error){setMessage(member.error.message);return}setName('');await load()}
  async function invite(){const sb=getSupabase();if(!sb||!organization||!email.includes('@')||!access.canManageOrganization)return;const {data:{session}}=await sb.auth.getSession();const user=session?.user;if(!user||!session)return;const {data:invitation,error}=await sb.from('organization_invitations').insert({organization_id:organization.id,email:email.trim().toLowerCase(),role,invited_by:user.id}).select('id').single();if(error){setMessage(error.message);return}const sent=await fetch('/api/invitations',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({invitationId:invitation.id})});const response=await sent.json().catch(()=>({}));setMessage(sent.ok?'Invitation email sent.':response.error||'Invitation recorded, but email delivery failed.');setEmail('');await load()}
  async function changeRole(userId:string,next:Role){const sb=getSupabase();if(!sb||!organization||next==='owner')return;const {error}=await sb.from('organization_members').update({role:next}).eq('organization_id',organization.id).eq('user_id',userId);setMessage(error?.message||'Role updated.');if(!error)await load()}
  if(loading)return <p className="empty-state">Loading organisation workspace…</p>;
  if(!organization)return <div className="space-y-5"><div className="operational-heading"><div className="eyebrow"><span className="eyebrow-dot"/> ORGANISATION</div><h1>Create your team workspace</h1><p>Establish an organisation before inviting colleagues and assigning controlled access.</p></div><div className="team-create"><Building2 size={20}/><div><strong>Organisation name</strong><p>This becomes the secure boundary for members and roles.</p></div><input value={name} onChange={e=>setName(e.target.value)} placeholder="Company name"/><button onClick={create}>Create workspace</button></div>{message&&<div className="configuration-note"><ShieldCheck size={17}/><div><strong>Setup status</strong><p>{message}</p></div></div>}</div>;
  return <div className="space-y-5"><div className="operational-heading"><div className="eyebrow"><span className="eyebrow-dot"/> ORGANISATION</div><h1>{organization.name}</h1><p>Manage membership and least-privilege access across this organisation.</p></div><div className="team-summary"><Users size={18}/><div><strong>{members.length} active member{members.length===1?'':'s'}</strong><p>{invitations.filter(i=>i.status==='pending').length} pending invitations</p></div><span>Role protected</span></div><section className="team-panel"><h2>Members</h2>{members.map(member=><div className="member-row" key={member.user_id}><div><strong>{member.email}</strong><small>{member.role==='owner'?'Organisation owner':'Workspace member'}</small></div>{member.role==='owner'?<b>Owner</b>:<select value={member.role} onChange={e=>changeRole(member.user_id,e.target.value as Role)}><option value="admin">Admin</option><option value="analyst">Analyst</option><option value="viewer">Viewer</option></select>}</div>)}</section><section className="team-panel"><h2>Invite a colleague</h2><div className="invite-row"><UserPlus size={18}/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="colleague@company.com"/><select value={role} onChange={e=>setRole(e.target.value as Exclude<Role,'owner'>)}><option value="admin">Admin</option><option value="analyst">Analyst</option><option value="viewer">Viewer</option></select><button onClick={invite}>Record invitation</button></div>{invitations.map(item=><div className="invitation-row" key={item.id}><span>{item.email}</span><b>{item.role}</b><small>{item.status}</small></div>)}</section>{message&&<div className="configuration-note"><ShieldCheck size={17}/><div><strong>Workspace status</strong><p>{message}</p></div></div>}</div>;
}
