import { useId, type ReactNode } from "react";
import type { KeyOptions } from "./geometry";
import { useActiveIndex, useElementWidth } from "./hooks";
import { CANNOT_SHOW } from "./summary";

/* ================================================================
   VERDIO — chart frame
   What every kit chart shares: the role="img" plot with its generated
   aria-label and keyboard model, the visually hidden live region, the
   'View this chart as a table' disclosure and the cannot-show state.
   ================================================================ */

export interface ChartTableData {
  caption: string;
  headers: string[];
  rows: string[][];       // the first cell of each row is the row header
}

export function ChartTable({ caption, headers, rows }: ChartTableData) {
  return (
    <details className="v2-kc-table">
      <summary>View this chart as a table</summary>
      <div className="v2-kc-tbl" tabIndex={0}>
        <table>
          <caption>{caption}</caption>
          <thead><tr>{headers.map(h => <th key={h} scope="col">{h}</th>)}</tr></thead>
          <tbody>{rows.map((cells, i) => <tr key={i}>{cells.map((c, j) => (j === 0 ? <th key={j} scope="row">{c}</th> : <td key={j}>{c}</td>))}</tr>)}</tbody>
        </table>
      </div>
    </details>
  );
}

export function CannotShow({ message = CANNOT_SHOW }: { message?: string }) {
  return <p className="v2-kc-empty" role="status">{message}</p>;
}

export interface ChartContext {
  width: number;                           // measured plot width in px; the SVG viewBox uses it 1:1
  active: number | null;                   // the shared activeIndex (pointer and keyboard)
  setActive: (i: number | null) => void;
}

interface ChartFrameProps {
  title?: string;
  subtitle?: string;
  label: string;                           // generated by summarise(), never hand-written
  available: boolean;
  unavailableMessage?: string;
  count: number;                           // points the keyboard can step through
  keyOptions?: KeyOptions;
  announce: (index: number) => string;     // text for the live region
  legend?: ReactNode;
  table: ChartTableData;
  fallbackWidth?: number;
  children: (ctx: ChartContext) => ReactNode;
}

export function ChartFrame({ title, subtitle, label, available, unavailableMessage, count, keyOptions, announce, legend, table, fallbackWidth = 560, children }: ChartFrameProps) {
  const [boxRef, width] = useElementWidth<HTMLDivElement>(fallbackWidth);
  const { active, setActive, plotProps } = useActiveIndex(available ? count : 0, keyOptions);
  const hintId = useId();
  const showTitle = title || subtitle;

  return (
    <figure className="v2-kc">
      {showTitle && (
        <figcaption className="v2-kc-head">
          {title && <p className="v2-kc-title">{title}</p>}
          {subtitle && <small>{subtitle}</small>}
        </figcaption>
      )}
      <div className="v2-kc-box" ref={boxRef}>
        {available ? (
          <>
            <div className="v2-kc-plot" role="img" aria-label={label} aria-describedby={hintId} {...plotProps}>
              {children({ width, active, setActive })}
            </div>
            <span id={hintId} className="v2-kc-live">Use the {keyOptions?.vertical ? 'up and down' : 'left and right'} arrow keys to step through the points, Home and End to jump to the first and last, Escape to clear.</span>
            <p className="v2-kc-live" aria-live="polite" aria-atomic="true">{active !== null ? announce(active) : ''}</p>
          </>
        ) : <CannotShow message={unavailableMessage} />}
      </div>
      {available && legend}
      {available && <ChartTable {...table} />}
    </figure>
  );
}
